# Site settings

title: Melody Zhao' Blog
# REQUIRED CHANGES
# Edit next line, providing your own name.
title: "Melody Zhao Blog"
# Edit next line, replacing 'techfolios' with your github username
url: "https://melody-coder923.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

# OPTIONAL CHANGES
# You might want to change the bio page label to something else, such as CV
bio-page-label: About
# You might want to change the theme associated with one or more sections of the site.
# Defining your own custom theme variations is easy. See the documentation.
theme-home: theme-home-builtin-1.html
theme-projects: theme-projects-builtin-1.html
theme-essays: theme-essays-builtin-1.html
theme-bio: theme-bio-builtin-2.html

# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: igorpro

# Blog settings
permalink: /blog/:categories/:title/

# Default settings
markdown: kramdown
include: [_data, _posts]

collections:
  posts:
    output: true
    permalink: /blog/:categories/:title/

defaults:
  - scope:
      path: "about.md"
    values:
      permalink: /
      layout: default
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post

# Post categories
category_dirs:
  - deep-learning
  - agentic-ai
  - full-stack

